### ISSUE TITLE
Consider bumping up high scores

### ISSUE THREAD

**Issue by udf2457** [spamhaus/spamassassin-dqs#41]
At present, your scores (perhaps especially sh_scores.cf) seem to be implemented on the basis of the default `required_score` of 5.

However, as per the SA docs (https://spamassassin.apache.org/full/3.2.x/doc/Mail_SpamAssassin_Conf.html):

> required_score n.nn (default: 5)
>     Set the score required before a mail is considered spam. n.nn can be an integer or a real number. 5.0 is the default setting, and is quite aggressive; it would be suitable for a single-user setup, but if you're an ISP installing SpamAssassin, you should probably set the default to be more conservative, like 8.0 or 10.0. It is not recommended to automatically delete or discard messages marked as spam, as your users will complain, but if you choose to do so, only delete messages with an exceptionally high score such as 15.0 or higher. This option was previously known as required_hits and that name is still accepted, but is deprecated. 

Given that most users of this github repo will be paid-up users of the DQS service (i.e. ISPs or corporates), I think it is only fair and reasonable to assume that most (or all) of them will have bumped up their `required_score` config from its default 5.  Therefore I think this repo should really reflect that and bump up the scores so that spam that would get caught under `5` get caught under higher settings ?

**Comment by ricalfieri** [comment]
Hello,

I managed quite a bit of multidomain mailservers in the past and always used the default score of 5. Sometimes I also lowered the required_score to 4 but YMMV.

Since this is a plugin meant to work out of the box on a default SA installation, bumping the scores is not something I'm comfortable with. 

Also, if a postmaster is experienced enough to modify the default installation, he'll be aware of the actual scores and would probably change them permanently by using a custom .cf files
